version: '2'
services:
  etcd:
    image: nginx
    container_name: nginx-lb
    hostname: nginx-lb
    volumes:
    - /root/kube-yaml/nginx-lb/nginx-lb.conf:/etc/nginx/nginx.conf
    ports:
    - 16443:16443
    restart: always
